version: "3.1"

networks:
  marvel_comics:
    driver: bridge

services:
  fixPermissions:
    image: docker.io/bitnami/postgresql:11.8.0-debian-10-r57
    user: root
    command: chown -R 1001:1001 /bitnami/postgresql
    volumes:
      - ./docker/data/pg:/bitnami/postgresql
  postgres:
    image: docker.io/bitnami/postgresql:11.8.0-debian-10-r57
    container_name: "marvel_comics_pg"
    restart: unless-stopped
    depends_on:
      - fixPermissions
    ports:
      - 5432:5432
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - ./docker/data/pg:/bitnami/postgresql
    networks:
      - marvel_comics

  app:
    container_name: "marvel_comics_app"
    build: .
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: ${DOCKER_APP_COMMAND}
    networks:
      - marvel_comics
